name: 'migueldamota/deploy'
description: Custom deployment

inputs:
  private-key:
    required: true
    description: SSH private key

  dir:
    required: true
    description: Directory

  host:
    required: true
    description: Host

  user:
    required: true
    description: User

  password:
    required: true
    description: Password

  port:
    default: 22
    description: Port

  token:
    required: true
    description: GitHub token

  after_deploy:
    description: Commands after deploy

  type:
    description: "Type of deployment (e.g: react)"

runs:
  using: 'node16'
  main: index.js
