name: 'migueldamota/deploy'
description: Custom deployment

inputs:
  private-key:
    required: true
    description: SSH private key

  dir:
    required: true
    description: Directory

  host:
    required: true
    description: Host

  user:
    required: true
    description: User

  password:
    required: true
    description: Password

  port:
    default: 22
    description: Port

runs:
  using: 'node16'
  main: index.js
